AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  text-analizer

  Sample SAM Template for text-analizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
Resources:
  TextAnalizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        TextAnalizer:
          Type: Api
          Properties:
            Path: /text-analizer
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TextAnalizerApi:
    Description: API Gateway endpoint URL for Prod stage for Text Analizer function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/TextAnalizer/"
  TextAnalizerFunction:
    Description: Text Analizer World Lambda Function ARN
    Value: !GetAtt TextAnalizerFunction.Arn
  TextAnalizerFunctionIamRole:
    Description: Implicit IAM Role created for Text Analizer function
    Value: !GetAtt TextAnalizerFunctionRole.Arn
